name: Chromium-macos run full tests suite
on:
  pull_request:
    branches: [ main ]

concurrency:
  group: pr-chromium-macos-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  playwright-chromium-macos:
    timeout-minutes: 90
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Build phoenix
      run: npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright unit tests in Chromium
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 12
        max_attempts: 3
        command: npm run testChromium

    - name: Run Playwright integration tests in Chromium
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 12
        max_attempts: 3
        command: npx cross-env TEST_ENV=integration npm run testChromium

    - name: Run Playwright mainview tests in Chromium
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 12
        max_attempts: 3
        command: npx cross-env TEST_ENV=mainview npm run testChromium

    - name: Run Playwright livepreview tests in Chromium
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 15
        max_attempts: 3
        command: npx cross-env TEST_ENV=livepreview npm run testChromium

    - name: Run Playwright LegacyInteg tests in Chromium
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 20
        max_attempts: 3
        command: npx cross-env TEST_ENV=LegacyInteg npm run testChromium
