name: Firefox-linux run full tests suite
on:
  pull_request:
    branches: [ main ]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  playwright-firefox-linux:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Build phoenix
      run: npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright unit tests in Firefox
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 12
        max_attempts: 3
        command: npm run testFirefox

    - name: Run Playwright integration tests in Firefox
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 12
        max_attempts: 3
        command: npx cross-env TEST_ENV=integration npm run testFirefox

    - name: Run Playwright mainview tests in Firefox
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 12
        max_attempts: 3
        command: npx cross-env TEST_ENV=mainview npm run testFirefox

    - name: Run Playwright livepreview tests in Firefox
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 15
        max_attempts: 3
        command: npx cross-env TEST_ENV=livepreview npm run testFirefox

    - name: Run Playwright LegacyInteg tests in Firefox
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 20
        max_attempts: 3
        command: npx cross-env TEST_ENV=LegacyInteg npm run testFirefox
