name: Chromium run integration tests suite with Playwright
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Build phoenix
      run: npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright integration tests in Chromium Attempt 1
      timeout-minutes: 30
      id: attemptC1
      continue-on-error: true
      run: npm run testIntegChromium

    - name: Run Playwright integration tests in Chromium Attempt 2
      if: steps.attemptC1.outcome == 'failure'
      id: attemptC2
      run: npm run testIntegChromium

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
