name: Chromium run unit tests suite with Playwright
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Build phoenix
      run: npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests in chromium
      run: npm run testChromium
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
