name: Chromium-windows prod release run full tests suite
# we only do this on windows on chrome as a sanity. detailed tests will be run on pulls on staging/prod branch
on:
  pull_request:
    branches: [ main ]

concurrency:
  group: pr-chromium-windows-prod-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  playwright-chromium-windows-prod:
    timeout-minutes: 90
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build phoenix
        run: |
          npm run build
          npm run release:prod
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright unit tests in Chromium for prod stage
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 12
          max_attempts: 3
          command: npm run testChromiumDist

      - name: Run Playwright integration tests in Chromium for prod stage
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 12
          max_attempts: 3
          command: npx cross-env TEST_ENV=integration npm run testChromiumDist

      - name: Run Playwright mainview tests in Chromium for prod stage
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 12
          max_attempts: 3
          command: npx cross-env TEST_ENV=mainview npm run testChromiumDist

      - name: Run Playwright livepreview tests in Chromium for prod stage
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: npx cross-env TEST_ENV=livepreview npm run testChromiumDist

      - name: Run Playwright LegacyInteg tests in Chromium for prod stage
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: npx cross-env TEST_ENV=LegacyInteg npm run testChromiumDist