name: Chromium run unit tests suite with Playwright
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Build phoenix
      run: npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright unit tests in Chromium Attempt 1
      id: attemptC1
      timeout-minutes: 20
      continue-on-error: true
      run: npm run testChromium

    - name: Run Playwright unit tests in Chromium Attempt 2
      id: attemptC2
      if: steps.attemptC1.outcome == 'failure'
      timeout-minutes: 30
      continue-on-error: true
      run: npm run testChromium

    - name: Run Playwright unit tests in Chromium Attempt 3
      id: attemptC3
      if: steps.attemptC2.outcome == 'failure'
      run: npm run testChromium

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
