name: Phoenix build verification

on:
  pull_request:
    branches: [ main ]

jobs:
  build-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Npm Install
        run: |
          npm ci
      - name: eslint using npm run eslint
        run: |
          npm run lint
      - name: building Phoenix with npm run build
        run: |
          npm run build
